version: '3.8'

services:
  readr:
    build: .
    image: "gjames8/readr:latest"
    ports:
      - "8080:8080"
    container_name: readr
    volumes:
      - ./data:/app/data
    restart: unless-stopped